[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "ws_game/dist"
command = "rustup default stable; rustup target add wasm32-unknown-unknown; rustup update stable; cargo install trunk --locked; trunk build ws_game/index.html --release"


[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/daily_challenge.tsv"
[headers.values]
Access-Control-Allow-Origin = "*"