[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[edge_functions]]
function = "og-param-proxy-daily"
path = "/daily/*"

[[edge_functions]]
function = "og-param-proxy-game"
path = "/game/*"

[build]
publish = "ws_web/dist"
command = "rustup default stable; rustup target add wasm32-unknown-unknown; rustup update stable; cargo install trunk --locked; trunk build ws_web/index.html --release --no-minification"


[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/daily.tsv"
[headers.values]
Access-Control-Allow-Origin = "*"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/news.yaml"
[headers.values]
Access-Control-Allow-Origin = "*"
