pub const IDEAL_WIDTH: f32 = 320.;
pub const IDEAL_HEIGHT: f32 = 568.;
pub const IDEAL_RATIO: f32 = IDEAL_WIDTH as f32 / IDEAL_HEIGHT as f32;

pub const TOP_BAR_HEIGHT: f32 = 50.;
pub const TOP_BAR_ICON_WIDTH: f32 = 25.;
pub const WORD_SALAD_LOGO_WIDTH: f32 = 160.;

pub const THEME_HEIGHT: f32 = 40.;
pub const THEME_WIDTH: f32 = GRID_SIZE;

pub const THEME_INFO_HEIGHT: f32 = 10.;
pub const THEME_INFO_WIDTH: f32 = 100.;

pub const TIMER_HEIGHT: f32 = 10.;
pub const TIMER_WIDTH: f32 = 40.;

pub const GRID_TILE_SIZE: f32 = 60.;
pub const GRID_GAP: f32 = 20.;
pub const GRID_SIZE: f32 = (GRID_TILE_SIZE * 4.0) + GRID_GAP;
pub const WORD_LIST_EXTRA_WIDTH: f32 = 20.0;

pub const WORD_LIST_HEIGHT: f32 = 108.;
pub const WORD_HEIGHT: f32 = 22.;
pub const WORD_WIDTH_PER_CHARACTER: f32 = 10.;
pub const WORD_WIDTH_FIXED: f32 = 20.;

pub const WORD_LIST_WIDTH: f32 = GRID_SIZE + WORD_LIST_EXTRA_WIDTH;
pub const WORD_MAIN_PAD: f32 = 10.;
pub const WORD_CROSS_PAD: f32 = 5.;

/// Extra top offset while streaming

pub const CONGRATS_ENTITY_STATISTIC_SIZE_NORMAL: f32 = 72.0;
pub const CONGRATS_ENTITY_STATISTIC_SIZE_SELFIE: f32 =
    CONGRATS_ENTITY_STATISTIC_SIZE_NORMAL * 2.0 / 3.0;

pub const CONGRATS_ENTITY_VERTICAL_GAP: f32 = 0.0;

pub const CONGRATS_ENTITY_BUTTON_HEIGHT: f32 = 35.0;
pub const CONGRATS_ENTITY_BUTTON_WIDTH_NORMAL: f32 = GRID_SIZE;
pub const CONGRATS_ENTITY_BUTTON_WIDTH_SELFIE: f32 = GRID_SIZE * 2.0 / 3.0;

pub const NON_LEVEL_TEXT_HEIGHT: f32 = 80.0;
pub const NON_LEVEL_TEXT_WIDTH: f32 = 240.0;

pub const NON_LEVEL_BUTTON_HEIGHT: f32 = 35.0;
pub const NON_LEVEL_BUTTON_WIDTH: f32 = GRID_SIZE;

pub const HINTS_POPUP_BOX_TOP: f32 = 180.;
pub const HINTS_POPUP_BOX_WIDTH: f32 = 300.;
pub const HINTS_POPUP_BOX_HEIGHT: f32 = 200.;

pub const HINTS_POPUP_BOX_TITLE_WIDTH: f32 = 280.;
pub const HINTS_POPUP_BOX_TITLE_HEIGHT: f32 = 40.;

pub const HINTS_POPUP_BOX_BUTTON_HEIGHT: f32 = 40.;
pub const HINTS_POPUP_BOX_BUTTON_WIDTH: f32 = 280.;

pub const SELFIE_POPUP_BOX_TOP: f32 = 180.;
pub const SELFIE_POPUP_BOX_WIDTH: f32 = 300.;
pub const SELFIE_POPUP_BOX_HEIGHT: f32 = 250.;

pub const SELFIE_POPUP_BOX_TITLE_WIDTH: f32 = 280.;
pub const SELFIE_POPUP_BOX_TITLE_HEIGHT: f32 = 60.;

pub const SELFIE_POPUP_BOX_BUTTON_HEIGHT: f32 = 43.;
pub const SELFIE_POPUP_BOX_BUTTON_WIDTH: f32 = 280.;
